### ISSUE TITLE
Constructor injection

### ISSUE THREAD

**Issue by dVaffection** [AdamBien/afterburner.fx#36]
Is there a way to use constructor injection? 

I'm not talking about presenters but other components, e.g. I have component A that depends on component B and my presenter depends on A component. So in order to inject A I have to inject B into A first. It all works well with `@Inject` annotation on fields, but what would be really nice to have is the possibility to explicitly specify B dependency on A constructor. 

I know I can use mockito `@InjectMocks` annotation in my unit tests but still I prefer the old-fashioned way to see class dependencies.

**Comment by AdamBien** [comment]
dVaffection -> I thought about that. However: I never used constructor injection in JavaEE project. I also never bumped to one in projects I reviewed.

I use package-private fields and setting the fields directly.
Just curious: what are you building with afterburner?

**Comment by dVaffection** [comment]
Hi @AdamBien,

Unfortunately I'm not working with afterburner anymore. My initial proposal was based on my experience with Spring framework.

**Comment by julianseeger** [comment]
Even though this topic is old and closed, it fits for my question:
I just implemented constructor injection using afterburner.fx and setting a custom instanceSupplier on the Injector, but is it true, that the javax.inject implementation of afterburner is not compatible with the specification because it is based on names instead of types?

Name based injection is problematic with constructors as you can't extract parameter names after compilation (I get arg0, arg1, ... when trying).

**Comment by tobiasdiez** [comment]
One question: is constructor injection now possible in 1.7? if yes, how?
