### ISSUE TITLE
Per view DI model/service conflict

### ISSUE THREAD

**Issue by jeanvc** [AdamBien/afterburner.fx#44]
Hi there,

I'm using a custom injection context for one of my presenters. The context contains a fully initialized instance of a non-primitive non-string type that should be injected into the presenter. Currently, this works only if the type is default-constructable. I'm using the latest release 1.6.1.

It seems that per view DI interferes with model/service injection as the field to inject will first be assigned a value from instantiateModelOrService before the custom injection context applies. The flow is roughly as follows:

instantiatePresenter(c, ic) -> registerExistingAndInject(i) -> injectAndInitialize(i) -> injectMembers(i) -> injectMembers(c, i)

In injectMembers(c, i), instantiateModelOrService will be called as the field's type is neither primitive nor string. After all fields have been injected, post-injection will kick in -- and overwrite the default-constructed instance with the one from the custom injection context.

Is this intended? If instantiateModelOrService was allowed to return null (which will never happen with the default instance supplier but can happen with a custom one) or could otherwise be skipped if no appropriate model or service can be found, unneeded instantiations would be prevented. Maybe this would cause trouble in other places, though.

**Comment by AdamBien** [comment]
I have to admit --> I found the error earlier but was too lazy to fix it. And: no one complained before. I wrote a couple of unit test and was able to reproduce and fix it. Please check the current snapshot whether it works for you as expected.

**Comment by dominic-jones** [comment]
If this has indeed been fixed in the latest snapshot, can we have a build of it pushed through to Central?

As of 1.6.2, this problem is still present (and was one of the first things I tried, injecting a third party class where I do not control the constructor).

Really liking the lightweight simplicity of Afterburner. In fact, it was extremely close to the MVP I was attempting to use with JavaFx already.

If there is no off-Central fix, I can see about contributing a patch.
